//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicianDirectoryService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhysicianDBEntities : DbContext
    {
        public PhysicianDBEntities()
            : base("name=PhysicianDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactInformation> ContactInformations { get; set; }
        public virtual DbSet<Physician> Physicians { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
    }
}
